function(add_example LIB_TARGET EXAMPLE_TARGET)
	find_package(spdlog REQUIRED)
	add_executable(${EXAMPLE_TARGET} examples/${EXAMPLE_TARGET}.cpp)
	target_link_libraries(${EXAMPLE_TARGET} PRIVATE ${LIB_TARGET} PRIVATE spdlog::spdlog)
	target_compile_features(${EXAMPLE_TARGET} PRIVATE cxx_std_20)
    install(TARGETS ${EXAMPLE_TARGET} DESTINATION examples)
endfunction()
