name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug', 'Release', 'RelWithDebInfo']
        config:
          - name: windows2022_msvc2022
            os: windows-2022
            compiler: visual_studio
            compiler_version: 17
            setup_build_env: 'call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"'
            activate_venv: 'call ".venv\\Scripts\\activate.bat"'

          - name: windows2019_msvc2019
            os: windows-2019
            compiler: visual_studio
            compiler_version: 16
            setup_build_env: 'call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"'
            activate_venv: 'call ".venv\\Scripts\\activate.bat"'

          - name: macos14_clang15
            os: macos-14
            compiler: clang
            compiler_version: 15
            setup_build_env: ""
            activate_venv: 'source .venv/bin/activate'

          - name: ubuntu2204_gcc12
            os: ubuntu-22.04
            compiler: gcc
            compiler_version: 12
            setup_build_env: ""
            activate_venv: 'source .venv/bin/activate'

          - name: ubuntu2204_clang15
            os: ubuntu-22.04
            compiler: clang
            compiler_version: 15
            setup_build_env: ""
            activate_venv: 'source .venv/bin/activate'

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }} ${{ matrix.build_type }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Python version
        if: matrix.config.os == 'windows-2022' || matrix.config.os == 'windows-2019' || matrix.config.os == 'ubuntu-22.04'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set Python version
        if: matrix.config.os == 'macos-14'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Cache Virtual Environment
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-${{ matrix.config.name }}-venv-${{ hashFiles('scripts/requirements.txt') }}

      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: .conan
          key: ${{ runner.os }}-${{ matrix.config.name }}-conan-${{ hashFiles('inference_client/conanfile.txt') }}

      - name: Setup Virtual Environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3 -m venv .venv
          ${{ matrix.config.activate_venv }}
          pip3 install -r scripts/requirements.txt

      - name: Setup Conan
        run: |
          ${{ matrix.config.activate_venv }}
          python3 scripts/conan/setup.py ${{ matrix.build_type }} ${{ matrix.config.compiler }} ${{ matrix.config.compiler_version }}

      - name: Build
        uses: ./.github/actions/shell
        with:
          commands: |
            ${{ matrix.config.activate_venv }}
            ${{ matrix.config.setup_build_env }}
            python3 scripts/cmake.py ${{ matrix.build_type }} ${{ matrix.config.compiler }} ${{ matrix.config.compiler_version }} --warnings
        env:
          CONAN_USER_HOME: ${{ github.workspace }}

      - name: Unit Tests
        uses: ./.github/actions/shell
        with:
          commands: |
            ${{ matrix.config.activate_venv }}
            ${{ matrix.config.setup_build_env }}
            python3 scripts/cmake.py ${{ matrix.build_type }} ${{ matrix.config.compiler }} ${{ matrix.config.compiler_version }} --warnings --coverage
            python3 scripts/tools/run_unit_tests.py ${{ matrix.build_type }}
        env:
          CONAN_USER_HOME: ${{ github.workspace }}
        continue-on-error: true
        timeout-minutes: 5

  #    - name: Publish Unit Tests Results
  #      uses: EnricoMi/publish-unit-test-result-action@v2
  #      if: always()
  #      with:
  #        files: results/unit_tests/unit_tests.xml
  #        fail_on: 'test failures'
  #        check_name: "Unit Tests Results - ${{ matrix.config.name }} ${{ matrix.build_type }}"

      - name: Code Coverage
        if: contains(matrix.config.os, 'ubuntu')
        run: |
          ${{ matrix.config.activate_venv }}
          ${{ matrix.config.setup_build_env }}
          python3 scripts/tools/run_coverage.py inference_client ${{ matrix.config.compiler }} ${{ matrix.config.compiler_version }}
        env:
          CONAN_USER_HOME: ${{ github.workspace }}
        timeout-minutes: 5

   #   - name: Upload coverage reports to Codecov
    #    if: contains(matrix.config.os, 'ubuntu')
  #      uses: codecov/codecov-action@v4
   #     with:
   #       file: results/coverage/cobertura.xml
   #       fail_ci_if_error: false
